### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by idan-h** [diommsantos/Gx64Sync#1]
```
C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\src\main\java\gsync\GSyncProvider.java:60: error: cannot find symbol
                        Messages.Session lastSession = sessionStatus.lastEntry().getValue();
                                                                    ^
  symbol:   method lastEntry()
  location: variable sessionStatus of type SortedMap<Integer,Session>
C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\src\main\java\gsync\GSyncProvider.java:80: error: cannot find symbol
                        Messages.Session lastSession = sessionStatus.lastEntry().getValue();
                                                                    ^
  symbol:   method lastEntry()
  location: variable sessionStatus of type SortedMap<Integer,Session>
C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\src\main\java\gsync\GSyncProvider.java:147: error: cannot find symbol
                updateSessionArea(sessionStatus.lastEntry().getValue().sessionName, sessionStatus.lastEntry().getValue().programName);
                                               ^
  symbol:   method lastEntry()
  location: variable sessionStatus of type SortedMap<Integer,Session>
C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\src\main\java\gsync\GSyncProvider.java:147: error: cannot find symbol
                updateSessionArea(sessionStatus.lastEntry().getValue().sessionName, sessionStatus.lastEntry().getValue().programName);
                                                                                                 ^
  symbol:   method lastEntry()
  location: variable sessionStatus of type SortedMap<Integer,Session>
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date
```

hey, seems like a cool project, I wanted to try - but I did not manage to succeed building.
I have gradle 8.8 - there are some java errors

 edit: I managed to get it working, this is an AWESOME project!
some small things to fix, but overall it works much better than ret-sync

**Comment by idan-h** [comment]
I managed to fix  that.

In the file `GSyncProvider.java` instead of `import java.util.SortedMap;` I used `import java.util.NavigableMap;`.  
Same for
`protected SortedMap<Integer, Messages.Session> sessionStatus = new TreeMap<Integer, Messages.Session>();` -
`protected NavigableMap<Integer, Messages.Session> sessionStatus = new TreeMap<Integer, Messages.Session>();`

**Comment by idan-h** [comment]
Another issue, is that I need to manually delete the folder -
```
C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync>gradle -PGHIDRA_INSTALL_DIR="C:\Users\idahe\OneDrive\Documents\ReverseEngineering\ghidra\ghidra_11.1.1_PUBLIC"
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.io.IOException: Unable to delete directory 'C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\build\classes\java\main'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\build\classes\java\main\gsync

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date
```

**Comment by diommsantos** [comment]
> ```
> C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\src\main\java\gsync\GSyncProvider.java:60: error: cannot find symbol
>                         Messages.Session lastSession = sessionStatus.lastEntry().getValue();
>                                                                     ^
>   symbol:   method lastEntry()
>   location: variable sessionStatus of type SortedMap<Integer,Session>
> C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\src\main\java\gsync\GSyncProvider.java:80: error: cannot find symbol
>                         Messages.Session lastSession = sessionStatus.lastEntry().getValue();
>                                                                     ^
>   symbol:   method lastEntry()
>   location: variable sessionStatus of type SortedMap<Integer,Session>
> C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\src\main\java\gsync\GSyncProvider.java:147: error: cannot find symbol
>                 updateSessionArea(sessionStatus.lastEntry().getValue().sessionName, sessionStatus.lastEntry().getValue().programName);
>                                                ^
>   symbol:   method lastEntry()
>   location: variable sessionStatus of type SortedMap<Integer,Session>
> C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\src\main\java\gsync\GSyncProvider.java:147: error: cannot find symbol
>                 updateSessionArea(sessionStatus.lastEntry().getValue().sessionName, sessionStatus.lastEntry().getValue().programName);
>                                                                                                  ^
>   symbol:   method lastEntry()
>   location: variable sessionStatus of type SortedMap<Integer,Session>
> 4 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileJava'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> > Run with --info option to get more log output.
> > Run with --scan to get full insights.
> 
> BUILD FAILED in 2s
> 2 actionable tasks: 1 executed, 1 up-to-date
> ```
> 
> hey, seems like a cool project, I wanted to try - but I did not manage to succeed building. I have gradle 8.8 - there are some java errors
> 
> edit: I managed to get it working, this is an AWESOME project! some small things to fix, but overall it works much better than ret-sync

This should now be fixed, I just replaced sortedMap with TreeMap.

**Comment by diommsantos** [comment]
> Another issue, is that I need to manually delete the folder -
> 
> ```
> C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync>gradle -PGHIDRA_INSTALL_DIR="C:\Users\idahe\OneDrive\Documents\ReverseEngineering\ghidra\ghidra_11.1.1_PUBLIC"
> > Task :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileJava'.
> > java.io.IOException: Unable to delete directory 'C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\build\classes\java\main'
>     Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
>     - C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\build\classes\java\main\gsync
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 1s
> 2 actionable tasks: 1 executed, 1 up-to-date
> ```

I have no idea how to fix this, the Gradle scripts are black magic generated by Ghidra. I did not create any Gradle script by myself.

**Comment by idan-h** [comment]
> > Another issue, is that I need to manually delete the folder -
> > ```
> > C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync>gradle -PGHIDRA_INSTALL_DIR="C:\Users\idahe\OneDrive\Documents\ReverseEngineering\ghidra\ghidra_11.1.1_PUBLIC"
> > > Task :compileJava FAILED
> > 
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':compileJava'.
> > > java.io.IOException: Unable to delete directory 'C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\build\classes\java\main'
> >     Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
> >     - C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\GSync\build\classes\java\main\gsync
> > 
> > * Try:
> > > Run with --stacktrace option to get the stack trace.
> > > Run with --info or --debug option to get more log output.
> > > Run with --scan to get full insights.
> > > Get more help at https://help.gradle.org.
> > 
> > BUILD FAILED in 1s
> > 2 actionable tasks: 1 executed, 1 up-to-date
> > ```
> 
> I have no idea how to fix this, the Gradle scripts are black magic generated by Ghidra. I did not create any Gradle script by myself.

I tested again right now, can't seem to reproduce, so I guess it was a temporary problem.

This is what ChatGPT suggested anyway:

```
task cleanBuildFolder(type: Delete) {
    delete 'build'
    doLast {
        int attempt = 0
        int maxAttempts = 5
        while (attempt < maxAttempts && buildDir.exists()) {
            try {
                delete buildDir
                println 'Build folder deleted successfully.'
                break
            } catch (Exception e) {
                println "Attempt ${attempt + 1} failed to delete build directory."
                Thread.sleep(1000) // wait for 1 second before retrying
                attempt++
            }
        }
        if (buildDir.exists()) {
            throw new GradleException('Failed to delete build folder after ' + maxAttempts + ' attempts.')
        }
    }
}
build.dependsOn cleanBuildFolder
```

inside `build.gradle`.

Might be unnecessary, let's see if this happens again. closing for now, and thanks!
