### ISSUE TITLE
HyperSync: It is not possible to sync the address. The node.napi.node module is not loaded!

### ISSUE THREAD

**Issue by lonsn2** [diommsantos/Gx64Sync#11]
HyperSync: It is not possible to sync the address. The node.napi.node module is not loaded!

When debugging any program, the log keeps showing this. What is the reason and how can it be resolved?

**Comment by diommsantos** [comment]
The reason for that I suppose (can't tell for sure without more information) is that you have HyperSync turned on and are disassembling node.napi.node in Ghidra, but the node.napi.node module is not loaded by the process you are currently debugging in x64Dbg. You can simply turn off HyperSync in either x64Dbg or Ghidra and that message will disappear. Or you can debug node.napi.node and HyperSync will sync Ghidra and x64Dbg.

**Comment by lonsn2** [comment]
Yes, I am debugging node.napi.node in x64DBg. The process has been loaded and stopped at the breakpoint of this process. After opening Hypersync, clicking on any line of code in x64DBg will display this prompt. Clicking on Sync location and Sync connection in x64DBg is unsuccessful.
My operation sequence is as follows:
1. Since node.napi.node is called by node.exe, when node.exe starts, attach node.exe in x64DBg, find node.napi.node from the "symbol" and set a breakpoint;
2. Continue running the program until the breakpoint in node.napi.node, and the top of the x64DBg window will display "Module: node.napi.node". At this point, clicking on any line of disassembly code in node.napi.node will display the line "It is not possible to sync the address" in the Ghidra log The node.napi.node module is not loaded!
3. At this point, the GSyncPlugin window displays:
Status: Connected
Debugger session: x64Dbg
Debugger program: node.exe
I should have made it clearer now. I don't know which step went wrong, please help me. Thank you!

**Comment by diommsantos** [comment]
Yes, so if you want to make it disappear you can either:
1. Turn off HyperSync
2. In Ghidra go to File -> Import file and import node.api.node

**Comment by lonsn2** [comment]
Of course, the node.api.node project file has been opened in Ghidra, and the GSyncPlugin window has been opened. The following is a screenshot, which indicates that the node.api.node project has been opened in Ghidra, and debugged to the node. api. node module interrupt in x64Dbg. At this time, when you click the assembly code in x64Dbg, the above prompt content will be output in the Ghidra log. Is there any problem with the operation?

**Comment by diommsantos** [comment]
That shouldn't happen then. Can you provide more specific details?

Some things to try:
- Are you sure the file is the same? HyperSync functions by comparing the hash file of the ghidra program and the hash file of the x64Dbg module. You can check wich module x64Dbg is using by going to the modules tabs and right click in node.napi.node and then copy full path.
- Did you patch the file in Ghidra ? Maybe it altered the MD5 of it and now HyperSync does not identify the file as being the same as in x64Dbg.
- Are you using the last Gx64Sync version? Older commits had some bugs that were fixed in the most recent version.
- What happens if when that message happens in Ghidra you turn off HyperSync and run the SyncLocation Command in x64Dbg?

**Comment by lonsn2** [comment]
Thank you for your reply.
Today, I re imported the node.api.node file into ghidra for analysis, and then debugged the node.api.node file in x64Dbg. The conclusions are as follows:
1. Ensure that the file paths in ghidra and x64DBg are exactly the same, and that this file has not been modified in any way;
2. The Gx64Sync I am currently using was downloaded from GitHub 3 days ago, and most of the files in it were modified on August 25, 2024 at 5:12, which should be the latest version;
3. When I turned off HyperSync and ran the SyncLocation command in x64Ddg, the message 'LayoutSync: It is not possible to sync the address' appeared in Ghidra The node.napi.node module is not loaded!
Later, I changed to a separate exe file for testing, and the result was still the same. This left me confused, where did the problem occur?
Could you please help me record a complete operation video? Thank you very much!

**Comment by diommsantos** [comment]
I genuinely have no clue what is going on then... Have you tried it with other executables? Does HyperSync work with other executables in your machine?

To record a complete operation video:
Record the following
1. Start Ghidra
2. Create New ghidra project
3. Import node.napi.node
4. Listen for connections in Ghidra's GSync
5. Start x64Dbg
6. Open node.napi.node in x64Dbg
7. Start HyperSync
8. Click in some instruction (preferably multiple times) in the disassembly in x64Dbg

Also if the program you are reversing does not have sensitive data nor is it malware you can send it to me at diommsantos@gmail.com to take a look.

**Comment by lonsn2** [comment]
I finally found the reason. In the analysis options window when analyzing the file, click on "Select All" and then analyze again.

**Comment by diommsantos** [comment]
So it works now? No more "It is not possible to sync the address" in the Ghidra log The node.napi.node module is not loaded!" messages? I will close the issue but I can reopen it in case the problem persists.

**Comment by unknown321** [comment]
same issue here

```json
[x64Sync] HyperSync: It is not possible to sync the address. The P]��< module is not loaded!

{"id":"rva","modHash":"7cc5f282b068f741adda2bb1076fb721","modName":"***.exe - .ProgramDB","rva":23681829}
{"id":"rva","modName":"***.exe","modHash":"ac22202adf114b2c2d39033c97d276e0","rva":23681891}
```

My exe is frequently patched outside of ghidra (a couple of bytes are changed), while ghidra version stays the same. Would it be possible to force sync no matter what? Updating ghidra with those changes is a chore.
