### ISSUE TITLE
x64dbg build errors

### ISSUE THREAD

**Issue by idan-h** [diommsantos/Gx64Sync#2]
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
Error	C1083	Cannot open include file: 'glaze/glaze.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\Messages.hpp	10		
Error	C1083	Cannot open include file: 'glaze/glaze.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\Messages.hpp	10		
Error	C1083	Cannot open include file: 'glaze/glaze.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\Messages.hpp	10		
Error	C1083	Cannot open include file: 'pluginsdk/bridgemain.h': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\pluginmain.h	11		
```

when trying to build either 64 or 86 versions via visual studio.

**Comment by idan-h** [comment]
also, the 64 version is missing from the release folder

**Comment by diommsantos** [comment]
> ```
> Severity	Code	Description	Project	File	Line	Suppression State	Details
> Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
> Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
> Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
> Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
> Error	C1083	Cannot open include file: 'asio/execution/allocator.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\asio\execution.hpp	18		
> Error	C1083	Cannot open include file: 'glaze/glaze.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\Messages.hpp	10		
> Error	C1083	Cannot open include file: 'glaze/glaze.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\Messages.hpp	10		
> Error	C1083	Cannot open include file: 'glaze/glaze.hpp': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\Messages.hpp	10		
> Error	C1083	Cannot open include file: 'pluginsdk/bridgemain.h': No such file or directory	x64Sync	C:\Users\idahe\OneDrive\Documents\ReverseEngineering\Gx64Sync-master\x64Sync\pluginmain.h	11		
> ```
> 
> when trying to build either 64 or 86 versions via visual studio.

I can't reproduce this error, using Visual Studio 2022 the solution compiles with no errors whatsoever. Maybe going to Solution Explorer -> Show All Files and including all the files not included in the project fixes it? I didn't do so because I didn't want to clutter my Solution Explorer view.

**Comment by diommsantos** [comment]
> also, the 64 version is missing from the release folder

I saw from #1 that you could alredy run Gx64Sync, but for any other person that ends up here the 64 version is not in the Release folder; it is in the x64 folder.

**Comment by idan-h** [comment]
For some reason files were missing on my pc. I cloned again and it solved
