### ISSUE TITLE
config.sync documentation is not clear

### ISSUE THREAD

**Issue by brandonros** [diommsantos/Gx64Sync#21]
On my machine with Ghidra, this is my config.sync:

```json
{
  "GSYNC_HOST": "10.5.5.2",
  "GSYNC_PORT": 9100,
  "X64SYNC_HOST": "10.5.5.1",
  "X64SYNC_PORT": 9100
}
```

On my machine with x64dbg, this is my config.sync:

```
{
  "GSYNC_HOST": "10.5.5.1",
  "GSYNC_PORT": 9100,
  "X64SYNC_HOST": "10.5.5.2",
  "X64SYNC_PORT": 9100
}
```

Notice how the IPs are flipped? It took me 20 minutes to figure out that needed to happen :D

**Comment by lmstearn** [comment]
Hi, just a check in the case where X64dbg and Ghidra are on the same machine, _config.sync_ is not required at all?
Wasn't sure about the Home directory on a Windows rig, C:\Users\username should be fine?
Thanks.
Edit: Looks like it is according to the log:

`[x64Sync] ConfigManager: Config file C:\Users\username\config.sync could not be open. Using default configurations.`

😃
