### ISSUE TITLE
Consider uploading pre-built versions

### ISSUE THREAD

**Issue by msm-code** [diommsantos/Gx64Sync#22]
Is there a reason other than lack of @diommsantos's time this repository has no builds available?

I assume Ghidra plugins are not bound to machine they were built on, so it's enough to build it once and upload to GH. My build attached below:

[ghidra_11.2.1_PUBLIC_20241221_GSync.zip](https://github.com/user-attachments/files/18219059/ghidra_11.2.1_PUBLIC_20241221_GSync.zip)

It's relatively easy to create a "release" on Github and attach a plugin as an attachment. You can reuse my build if you'd like.

**Comment by asareynolds** [comment]
> My build attached below:
> 
> [ghidra_11.2.1_PUBLIC_20241221_GSync.zip](https://github.com/user-attachments/files/18219059/ghidra_11.2.1_PUBLIC_20241221_GSync.zip)

Just a question on your build, it appears that it does not contain the `Gx64Sync\GSync\dist\ghidra_*_GSync.zip` file: how would one go about installing this build for Ghidra?

**Comment by diommsantos** [comment]
Yeah just lack of time. I'll see if I can create a release with your attachment. Thank you!

**Comment by unknown321** [comment]
x64dbg release is missing, but still available here - https://github.com/diommsantos/Gx64Sync/commit/e39c4c5ac9e0f72cfe86f37304a3d33dae82c5a0
