### ISSUE TITLE
Option for remote connection not only localhost

### ISSUE THREAD

**Issue by mirek186** [diommsantos/Gx64Sync#4]
Hi, In a scenario where Ghidra is e.g. on Kali, and you have to remote Windows machine, it would be awesome to have an option for a remote connection.
I've found a way to listen on the Ghidra side on all interfaces with a simple change in Listener.java
```
        this.serverSocket = new ServerSocket(PORT, 0, InetAddress.getByAddress(new byte[] {0x00,0x00,0x00,0x00}));
```
and it does work. However passing arguments from x64dbg it's a bit harder and I don't know enough about the plugin structure and how to pass arguments, so I wonder if you could add an option to pass args, e.g.
```
x64SyncConnect 192.168.56.101
```

**Comment by diommsantos** [comment]
As a quick fix if you have Visual Studio installed you can open the file [Client.hpp](https://github.com/diommsantos/Gx64Sync/blob/master/x64Sync/Client.hpp) and change the ip and port it tries to connect to.
Noetheless I will add as soon as possible support for a config file to set these settings without being necessary to recompile.

**Comment by diommsantos** [comment]
Now is possible to add `config.sync` file that should be able to solve your issue. In this case create a `config.sync` in your remote Windows machine user profile directory with the X64SYNC_PORT and X64SYNC_HOST properties. See [Configuration](https://github.com/diommsantos/Gx64Sync?tab=readme-ov-file#configuration) for more details.
