### ISSUE TITLE
Trojan alert for PluginDevBuildTool.exe

### ISSUE THREAD

**Issue by idan-h** [diommsantos/Gx64Sync#5]
Hey, what is this file?
It gets flagged as a trojan, and the calls it makes are weird

https://www.virustotal.com/gui/file/3ada80cacda5e82adfe3bea72fcabf62e267700d846a7351913b18ac27c527d3

**Comment by diommsantos** [comment]
This file is the result of the compilation of the project https://github.com/x64dbg/PluginDevHelper. You can delete it and follow the instructions on the linked repository if you want to compile your own.

**Comment by idan-h** [comment]
ok, I did the same testing and got similar results.
it is probably a false positive.

what is weird for me is all the calls that it does over the network, I don't see any external ip calls in the code itself..

https://www.virustotal.com/gui/file/610ab4b0a7c8529254ffc894256a0f77621c975c6014a5d799d4e8c1e330ea9b/behavior

**Comment by diommsantos** [comment]
I don't know why it makes external ip calls. I just clicked on "Compile Solution" to obtain the PluginDevBuild.exe, didn't even bother to look at the source code. A fast way to check if the file got infected (which I very much doubt) is to compile PluginDevBuild.exe yourself, submit it again to virus total and see if the external ip calls are still there.

**Comment by idan-h** [comment]
> I don't know why it makes external ip calls. I just clicked on "Compile Solution" to obtain the PluginDevBuild.exe, didn't even bother to look at the source code. A fast way to check if the file got infected (which I very much doubt) is to compile PluginDevBuild.exe yourself, submit it again to virus total and see if the external ip calls are still there.

yea, I did. this is my file above, and it still makes those calls.. I don't understand how could this be a false positive tho, as it has to make those calls so it will be recorded..

**Comment by diommsantos** [comment]
This is also very unlikely but maybe is a bug in Virus Total? I have no clue whatsoever about the external calls. Maybe opening an issue in [https://github.com/x64dbg/PluginDevHelper](https://github.com/x64dbg/PluginDevHelper) regarding the external calls would not be a bad idea.
